export const en = {
  common: {
    confirm: "Confirm",
    cancel: "Cancel",
    delete: "Delete",
    back: "Back"
  },
  admin: {
    dashboard_home: {
      booking_system: "BOOKING SYSTEM",
      current_status: "Current Status",
      status_open: "OPEN",
      status_closed: "CLOSED",
      open_close_booking: "Open/Close Booking",
      create_new_booking: "Create New Booking",
      broadcast_news: "Broadcast News",
      export_data: "Export Data",
      total_customers: "TOTAL CUSTOMERS",
      total_bookings: "TOTAL BOOKINGS",
      remaining_capacity: "REMAINING CAPACITY",
      booked_label: "BOOKED",
      total_label: "TOTAL",
      peak_engagement: "Peak Engagement Period",
      peak_engagement_desc: "Capacity utilization is at its highest during Saturday morning sessions. Consider opening additional time slots.",
      trending_up: "TRENDING UP ↑",
      recent_bookings: "Recent Bookings",
      view_all: "VIEW ALL",
      table_customer: "Customer",
      table_service: "Service",
      table_date: "Date",
      table_status: "Status",
      nav_dashboard: "Dashboard",
      nav_bookings: "Bookings",
      nav_customers: "Customers",
      nav_settings: "Settings"
    },
    manage_users: {
      empty_title: "No Customers Found",
      empty_desc: "Add a customer to see them listed here."
    },
    add_new_customer: {
      back_to_customers: "Back to Customers",
      add_new_member: "Add New Member",
      subtitle: "Invite a new individual to the Sacred Spaces community. Please ensure the phone number is accurate to facilitate seamless communication.",
      full_name_label: "Full Name",
      full_name_placeholder: "Enter first and last name",
      phone_number_label: "Phone Number",
      phone_number_placeholder: "98765 43210",
      info_text: "Adding a member allows them to receive booking confirmations and spiritual session reminders directly via SMS and WhatsApp.",
      add_customer_button: "Add Customer",
      cancel_button: "Cancel",
      adding: "Adding...",
      success_message: "Member Added!",
      error_name: "Name is required",
      error_phone: "Please enter a valid 10-digit phone number"
    },
    manage_sessions: {
      title: "Manage Sessions",
      subtitle: "Oversee and organize the spiritual calendar.",
      session_date: "Session Date",
      booking_date: "Booking Date",
      booking_time: "Booking Time",
      create_button: "CREATE NEW SESSION",
      filter_all: "ALL SESSIONS",
      filter_active: "ACTIVE",
      filter_drafts: "DRAFTS",
      filter_past: "PAST",
      published_by: "PUBLISHED BY",
      schedule_title: "Schedule Future Event",
      schedule_desc: "Add a new recurring or one-time session to the calendar.",
      cancel_title: "Cancel Session",
      cancel_desc: "Are you sure you want to cancel this session? This action cannot be undone."
    },
    create_session: {
      title: "Create New Session",
      subtitle: "Configure details for your community spiritual gathering.",
      publish_loading: "Publishing...",
      publish_btn: "Create & Publish",
      save_draft_btn: "Save as Draft",
      session_title_label: "Session Title",
      session_title_placeholder: "e.g., Wednesday Evening Meditation",
      event_day_label: "Event Day (Session Date)",
      event_day_desc: "When the actual spiritual gathering will take place.",
      location_label: "LOCATION",
      location_loading: "Loading...",
      location_placeholder: "Select location",
      seats_label: "SEATS",
      max_user_label: "MAX/USER",
      booking_open_label: "Booking Window Open Date",
      booking_open_desc: "When users can start booking seats. Must be strictly before the Event Day.",
      booking_start_time: "Booking Start Time",
      booking_end_time: "Booking End Time",
      error_title_req: "Session Title is required",
      error_location_req: "Location is required",
      error_tokens_min: "Tokens must be at least 1",
      error_max_users_min: "Max users per booking must be at least 1",
      error_time_gap: "End time must be at least 1 hour after start time."
    }
  },
  user: {
    home_booking_status: {
      welcome: "Welcome, Brother",
      subtitle: "Find your next moment of spiritual connection and community gathering below.",
      available_sessions: "Available Sessions",
      booking_open: "Booking Open",
      coming_up: "Coming Up This Sunday",
      slots_left: "{{count}} Slots Left",
      reserve_seat: "Reserve Your Seat",
      view_all: "View All Sessions",
      no_active_bookings: "No Active Bookings",
      empty_desc: "All current sessions are fully booked or completed. Check back later for upcoming sessions.",
      notify_me: "Notify Me of New Slots"
    },
    my_bookings: {
      title: "My Bookings",
      active_session: "Active Session",
      session_today: "Session Today",
      time: "TIME",
      token: "TOKEN",
      scan_at_entry: "SCAN AT ENTRY",
      get_directions: "Get Directions",
      cancel_booking: "Cancel Booking",
      past_bookings: "Past Bookings",
      filter: "Filter",
      load_more: "Load More History",
      cancel_confirm_title: "Cancel Booking?",
      cancel_confirm_msg: "Are you sure you want to cancel your booking for {{session}}? This action cannot be undone.",
      cancel_confirm_ok: "Cancel Booking",
      cancel_confirm_cancel: "Keep Booking",
      cancel_success: "Booking cancelled successfully.",
      status_confirmed: "CONFIRMED",
      status_completed: "COMPLETED",
      status_cancelled: "CANCELLED",
      no_active_booking: "No Active Booking",
      empty_desc: "You have no upcoming sessions booked."
    },
    login: {
      welcome_back: "Welcome back",
      phone_subtitle: "Please enter your registered phone number to continue your journey.",
      phone_label: "Phone Number",
      phone_placeholder: "555 0123",
      restriction_info: "Access is limited to numbers pre-registered by the community administrators.",
      login_button: "Login",
      need_help: "Need help accessing your account?",
      error_phone: "Please enter a valid 10-digit phone number",
      sending_otp: "Sending OTP..."
    },
    otp_verification: {
      title: "Verify Code",
      subtitle: "We've sent a 6-digit verification code to {{phone}}.",
      code_label: "Verification Code",
      verify_button: "Verify & Continue",
      resend_text: "Resend Code",
      resend_timer: "Resend Code in {{seconds}}s",
      verifying: "Verifying...",
      error_otp: "OTP must be 6 digits"
    },
    profile: {
      title: "Profile",
      name_label: "Name",
      phone_label: "Phone Number",
      status_label: "Community Status",
      status_value: "Active Member",
      member_since: "Member Since: Oct 2023",
      logout_btn: "Logout"
    },
    booking_successful: {
      confirmed_title: "Booking Confirmed!",
      confirmed_desc: "Your space in the sanctuary is reserved.",
      booking_id_label: "Booking ID",
      token_no_label: "Token No.",
      date_label: "Date",
      time_label: "Time",
      attendees_label: "Attendees",
      attendees_val: "2 People",
      hall_label: "Hall",
      hall_val: "Main Chapel",
      info_footer: "Please arrive 15 minutes before your scheduled time for check-in.",
      add_to_calendar: "Add to Calendar",
      view_all_bookings: "View All Bookings",
      back_to_home: "Back to Home"
    },
    book_session: {
      title: "Book Session",
      select_seats: "Select Number of Seats",
      choose_desc: "Choose how many seats you want to reserve (max 5 seats).",
      tokens_label: "Tokens required:",
      tokens_value: "25 per seat",
      disclaimer: "By reserving, you agree to attend the community prayer session.",
      confirm_btn: "Confirm Reservation",
      error_max: "Cannot select more than {{max}} seats.",
      error_min: "Minimum 1 seat is required."
    },
    errors: {
      server_error: "Something went wrong. Please try again.",
      network_error: "Connection problem. Please check your network."
    },
    debugger: {
      title: "API Logs Debugger",
      clear: "Clear All",
      close: "Close",
      no_logs: "No API logs yet. Make requests to populate.",
      req_payload: "Request Data:",
      res_payload: "Response Data:",
      duration: "Duration: {{ms}}ms",
      status: "Status: {{status}}",
      endpoint: "Endpoint: {{url}}"
    }
  }
};

export const hi: typeof en = { ...en };
