export const theme = {
  colors: {
    tertiary_fixed_dim: "#c6c6c7",
    surface_variant: "#e3e2e2",
    tertiary_container: "#b1b2b2",
    surface_container_lowest: "#ffffff",
    on_tertiary_fixed_variant: "#454747",
    secondary: "#4c56af",
    secondary_container: "#959efd",
    tertiary_fixed: "#e2e2e2",
    surface_dim: "#dbdad9",
    surface_bright: "#fbf9f9",
    surface_container_low: "#f5f3f3",
    on_tertiary_fixed: "#1a1c1c",
    on_primary_fixed: "#2e1500",
    on_primary_fixed_variant: "#6d3a00",
    primary_fixed_dim: "#ffb77a",
    on_primary_container: "#693800",
    inverse_primary: "#ffb77a",
    on_tertiary_container: "#434545",
    outline_variant: "#dbc2b0",
    outline: "#887364",
    on_surface: "#1b1c1c",
    on_secondary: "#ffffff",
    on_error: "#ffffff",
    on_background: "#1b1c1c",
    secondary_fixed: "#e0e0ff",
    on_tertiary: "#ffffff",
    tertiary: "#5d5f5f",
    on_error_container: "#93000a",
    on_secondary_fixed_variant: "#343d96",
    surface_container: "#efeded",
    on_secondary_fixed: "#000767",
    primary_container: "#ff9933",
    on_surface_variant: "#554336",
    error: "#ba1a1a",
    surface_container_high: "#e9e8e7",
    on_secondary_container: "#27308a",
    error_container: "#ffdad6",
    primary: "#8f4e00",
    surface_container_highest: "#e3e2e2",
    surface_tint: "#8f4e00",
    inverse_on_surface: "#f2f0f0",
    on_primary: "#ffffff",
    surface: "#fbf9f9",
    primary_fixed: "#ffdcc2",
    background: "#fbf9f9",
    secondary_fixed_dim: "#bdc2ff",
    inverse_surface: "#303031",
    truecaller: "#0052ff"
  },
  typography: {
    headline_lg_mobile: {
      fontFamily: 'Inter',
      fontSize: 24,
      fontWeight: '700',
      lineHeight: 32,
      letterSpacing: -0.24,
    },
    body_lg: {
      fontFamily: 'Inter',
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 24,
    },
    headline_md: {
      fontFamily: 'Inter',
      fontSize: 20,
      fontWeight: '600',
      lineHeight: 28,
    },
    headline_lg: {
      fontFamily: 'Inter',
      fontSize: 32,
      fontWeight: '700',
      lineHeight: 40,
      letterSpacing: -0.64,
    },
    body_sm: {
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: '400',
      lineHeight: 20,
    },
    status_label: {
      fontFamily: 'Inter',
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 16,
    },
    label_caps: {
      fontFamily: 'Inter',
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 16,
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    }
  },
  spacing: {
    lg: 24,
    xl: 32,
    margin_mobile: 20,
    gutter: 16,
    base: 4,
    sm: 8,
    md: 16,
    xs: 4
  },
  rounded: {
    sm: 4,
    DEFAULT: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999
  }
} as const;

export type ThemeType = typeof theme;
